# Generated by Django 3.2.8 on 2023-05-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0009_perfil_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
